config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  resources :users, only: [:show, :edit, :update]
  get 'books/new'
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get '/home/about', to: 'homes#about'
  get '/home/users', to: 'users#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :books, only: [:new, :create, :index, :show, :destroy] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates_associated :books

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book =Book.new(book_params)
    if @book.save
      redirect_to @book, notice:'投稿されました'
    else
      render :new
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_path(@book.id)
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @books = @user
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to book_path(book.id)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(current_user.id)
    @user.update(user_params)
    redirect_to user_path(current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h1>User info</h1>
<div class="profile_container">
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <h4>name</h4>
  <h4 class="profile-name"><%= user.name %></h4>
  <h4>introduction</h4>
  <h4 class="profile-body"><%= current_user.introduction %></h4>
  <% if user.id == current_user.id %>
  <p><%= link_to "プロフィール編集", edit_user_path(user) %></p>
  <% end %>
</div>

<h1>New book</h1>
<%= form_with model: book, url:'/books', local:true do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>
<br>
  <%= f.submit 'Create Book', class: "btn btn-success" %>
</br>
<% end %>

app/views/books/edit.html.erb
<div class="container">
    <div class="row">
       <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
         <h1>Editing Book</h1>
         <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
         <h4>Title</h4>
         <%= f.text_field :title %>
         <h4>Opinion</h4>
         <%= f.text_area :body %>
         <br><%= f.submit 'Update Book', class: "btn btn-success" %></br>
         <% end %>
         <%= link_to "Show", book_path(@book.id) %>
         |
         <%= link_to "Back", books_path %>
       </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <%= render 'books/list', book: @book, user: @user %>
    </div>
    <div class="col-lg-8">
      <h1>Books</h1>
      <table class="table table-striped">
        <thead>
          <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
         <% @books.each do |book| %>
         <tr>
           <td class="profile_container">
            <%= attachment_image_tag @user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %>
           </td>
           <td><%= link_to book.title, "/books/#{book.id}" %></td>
           <td><%= book.body %></td>
         </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <%= render 'books/list', book: @book, user: @user %>
        </div>
        <div class="col-lg-8">
          <h2>Book detail</h2>
          <table class="table table-striped">
              <tbody>
                  <tr>
                    <td class="profile_container">
                       <%= attachment_image_tag @user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
                       <br>
                         <%= link_to @user.name, "/users/#{@user.id}" %>
                       </br>
                    </td>
                    <td>
                       <%= link_to @book.title, "/books/#{@book.id}" %>
                    </td>
                    <td>
                       <%= @book.body %>
                    </td>
                    <td>
                       <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %>
                    </td>
                    <td>
                       <%= link_to "Destroy", book_path(@book), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
                    </td>
                  </tr>
              </tbody>
          </table>
        </div>
    </div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to Bookers!</h1>

<h5>CopyRight Infratop.inc</h5>

app/views/homes/top.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to Bookers !!</h1>
        <p>In
          <strong>Bookers</strong>
        </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <li>
              <%= link_to "Log in", new_user_session_path %>
            </li>
          </div>
          <div class="row">
            <li>
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-4" href="/"><%= link_to "Bookers", root_path %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Home", user_path(current_user.id) %>
              </li>
              <li class="nav-item">
                <%= link_to 'Users', home_users_path %>
              </li>
              <li class="nav-item">
                <%= link_to "Books", books_path %>
              </li>
              <li class="nav-item">
                <%= link_to "logout", destroy_user_session_path, method: :delete %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to "Home", root_path %>
              </li>
              <li class="nav-item">
                <%= link_to "About", home_about_path %>
              </li>
              <li class="nav-item">
                <%= link_to "sign up", new_user_registration_path %>
              </li>
              <li class="nav-item">
                <%= link_to "login", new_user_session_path %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h2>User info</h2>
            <%= form_with model:@user, local:true do |f| %>
            <label for="inputName">Name</label>
            <br>
              <%= f.text_field :name, autofocus: true, id:"inputName"%>
            </br>
            <label for="inputImage">Image</label>
            <br>
              <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
            </br>
            <label for="inputIntroduction">Introduction</label>
            <br>
              <%= f.text_field :introduction %>
            </br>
            <br>
              <%= f.submit "Update User", class: "btn btn-secondary" %>
            </br>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <%= render 'books/list', book: @book, user: @user %>
    </div>
    <div class="col-lg-8">
      <h1>Users</h1>
      <% @users.each do |user| %>
      <table class="table table-striped">
        <thead>
         <tr>
          <th>image</th>
          <th>name</th>
         </tr>
        </thead>
        <tbody>
          <tr>
           <td class="profile_container">
             <%= attachment_image_tag @user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %>
           </td>
           <td class="profile-name">
             <%= @user.name %>
           </td>
           <td>
             <%= link_to "Show", user_path(current_user.id) %>
           </td>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <%= render 'books/list', book: @book, user: @user %>
    </div>
    <div class="col-lg-8">
      <h1>Books</h1>
      <table class="table table-striped">
        <thead>
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
         </tr>
        </thead>
        <tbody>
         <% @books.each do |book| %>
         <tr>
           <td class="profile_container">
             <%= attachment_image_tag @user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %>
           </td>
           <td><%= link_to book.title, "/books/#{book.id}" %></td>
           <td><%= book.body %></td>
         </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>